services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trivia1
      MONGO_INITDB_DATABASE: trivia
    volumes:
      - mongodb_data:/data/db
    restart: on-failure:0

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.6
    environment:
      QUERY_DEFAULTS_LIMIT: 30
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'text2vec-openai'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0

  quiz-genai:
    container_name: quiz-genai
    build:
      context: ./genai
      dockerfile: ./Dockerfile
    env_file:
      - genai/.env
    environment:
      DEBUG: false
      WEAVIATE_HOST: weaviate
      EMBEDDING_MODEL: text-embedding-3-small
    depends_on:
      - weaviate
      - mongodb

  game-server:
    container_name: game-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
        - mongodb
        - quiz-genai
    env_file:
      - server/.env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:trivia1@mongodb:27017/trivia?authSource=admin
      QUIZGENAI_ENDPOINT: http://quiz-genai:3000

  game-client:
    container_name: game-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - client/.env
    environment:
      NODE_ENV: production
      COLYSEUS_ENDPOINT: http://game-server:2567
    ports:
        - "3000:80"
    depends_on:
        - game-server

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - game-client
      - game-server
      - quiz-genai

volumes:
  mongodb_data:
  weaviate_data:
