
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trivia1
      MONGO_INITDB_DATABASE: trivia
    ports:
      - "27108:27017"
    volumes:
      - ./.data/mongodb:/data/db

volumes:
  mongodb:
