
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trivia1
      MONGO_INITDB_DATABASE: trivia
    ports:
      - "27108:27017"
    volumes:
      - ./.data/mongodb:/data/db

  game-server:
    container_name: game-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        - mongodb

  game-client:
    container_name: game-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
        - "3000:3000"
    depends_on:
        - game-server

volumes:
  mongodb:
