services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: trivia1
      MONGO_INITDB_DATABASE: trivia
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: on-failure:0

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.28.0
    environment:
      QUERY_DEFAULTS_LIMIT: 30
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'text2vec-openai'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.29-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: on-failure:0

  quiz-genai-api:
    container_name: quiz-genai-api
    build:
      context: ./genai
      dockerfile: ./Dockerfile
    env_file:
      - genai/.env
    environment:
      DEBUG: false
      APP_TYPE: api
      WEAVIATE_HOST: weaviate
      RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672
      EMBEDDING_MODEL: text-embedding-3-small
      STRUCTURED_MODEL: deepseek-chat
    depends_on:
      - weaviate
      - mongodb
      - quiz-genai-worker
    restart: on-failure:0

  quiz-genai-worker:
    container_name: quiz-genai-worker
    build:
      context: ./genai
      dockerfile: ./Dockerfile
    env_file:
      - genai/.env
    environment:
      DEBUG: false
      APP_TYPE: worker
      WEAVIATE_HOST: weaviate
      RABBITMQ_DSN: amqp://guest:guest@rabbitmq:5672
      EMBEDDING_MODEL: text-embedding-3-small
      STRUCTURED_MODEL: deepseek-chat
    depends_on:
      - weaviate
    restart: on-failure:0

  lofi-icecast:
    image: moul/icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=ice
      - ICECAST_ADMIN_PASSWORD=ice
      - ICECAST_PASSWORD=ice
      - ICECAST_RELAY_PASSWORD=ice
      - ICECAST_HOSTNAME=ice
    restart: on-failure:0

  lofi-encoder:
    build:
        context: ./lofi
        dockerfile: ./Dockerfile
    volumes:
      - ./lofi/music:/app/music
      - ./lofi/playlist.txt:/app/playlist.txt
    container_name: radio-stream
    depends_on:
      - lofi-icecast
    restart: on-failure:0

  game-server:
    container_name: game-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
        - mongodb
        - quiz-genai-api
    env_file:
      - server/.env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:trivia1@mongodb:27017/trivia?authSource=admin
      QUIZGENAI_ENDPOINT: http://quiz-genai-api:3000
    restart: on-failure:0

  game-client:
    container_name: game-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file:
      - client/.env
    environment:
      VITE_NODE_ENV: production
      COLYSEUS_ENDPOINT: http://game-server:2567
      VITE_LIVESTREAM_ENDPOINT: streaming-genai-trivia.protons.buzz
    depends_on:
        - game-server
    restart: on-failure:0

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - game-client
      - game-server
      - quiz-genai-api

volumes:
  mongodb_data:
  weaviate_data:
