[tool.poetry]
name = "quiz-genai"
version = "0.1.0"
description = ""
authors = ["Protons (proton98)"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
